export const EventCategoryList = [
  {
    id: 1,
    title: "Visual Arts",
    url: "visual-arts",
    img: "events/photography.jpg",
  },
  {
    id: 2,
    title: "Performing Arts",
    url: "performing-arts",
    img: "events/dance.jpg",
  },
  {
    id: 3,
    title: "Musical Arts",
    url: "muzical-arts",
    img: "events/music.jpg",
  },
  {
    id: 4,
    title: "Game Zone",
    url: "gaming-zone",
    img: "events/gaming.jpg",
  },
  {
    id: 5,
    title: "Others",
    url: "others",
    img: "events/other.jpg",
  },
];

export const VisualEvents = [
  {
    event: "Live Photography",
    time: "9:00 am onwards, Both Days",
    venue: "Campus",
    image: "",
    url: "photography",
  },
  {
    event: "30 Sec Reels Making Competition",
    time: "9:00 am onwards, Both Days",
    venue: "Campus",
    image: "",
    url: "",
  },
  {
    event: "Wall Painting (Theme- Beautiful Kashmir)",
    time: "9:00 am, Day-1",
    venue: "Compound Wall",
    image: "",
    url: "",
  },
  {
    event: "Face Painting",
    time: "9:00 am, Day-1",
    venue: "LH",
    image: "",
    url: "",
  },
  {
    event: "Stone Painting",
    time: "9:00 am, Day-1",
    venue: "LH",
    image: "",
    url: "",
  },
  {
    event: "Portrait Sketching",
    time: "2:00 pm, Day-1",
    venue: "DH-3",
    image: "",
    url: "",
  },
  {
    event: "Clay Art",
    time: "2:00 pm, Day-1",
    venue: "LH",
    image: "",
    url: "",
  },
  {
    event: "Wall Painting (Theme - Festival of India)",
    time: "9:00 am, Day-2",
    venue: "Compound Wall",
    image: "",
    url: "",
  },
  {
    event: "Meme Making",
    time: "3:30 pm, Day-2",
    venue: "HT-1",
    image: "",
    url: "",
  },
];

export var MuzicalEvents = [
  {
    event: "Solo Song Eastern",
    time: "2:00 pm, Day-1",
    venue: "Common Hall",
    image: "",
    url: "",
  },
  {
    event: "Solo Song Western",
    time: "10:15 am, Day-2",
    venue: "Open Mic Stage",
    image: "",
    url: "",
  },
  {
    event: "Solo Regional Instrumental",
    time: "11:30 am, Day-1",
    venue: "Open Mic Stage",
    image: "",
    url: "",
  },
  {
    event: "Duet Song",
    time: "2:00 pm, Day-1",
    venue: "Open Mic Stage",
    image: "",
    url: "",
  },
  {
    event: "Rap",
    time: "12:30 pm, Day-1",
    venue: "Open Mic Stage",
    image: "",
    url: "",
  },
  {
    event: "Battle Of Bands",
    time: "6:00 pm, Day-1",
    venue: "Main Stage",
    image: "",
    url: "",
  },
  {
    event: "BeatBox",
    time: "11:30 am, Day-2",
    venue: "Open Mic Stage",
    image: "",
    url: "",
  },
  {
    event: "Ladi Shah (Story telling )",
    time: "1:30 pm, Day-2",
    venue: "HT-2",
    image: "",
    url: "",
  },
  {
    event: "Acapella (Group Singing)",
    time: "3:00 pm, Day-2",
    venue: "Main Stage",
    image: "",
    url: "",
  },
];

export var gamingEvents = [
  {
    event: "Gaming Zone",
    time: "9:00 am, Both Days",
    venue: "PF",
    image: "",
    url: "",
  },
];

export var OtherEvents = [
  {
    event: "The Trained Cuisine (North)",
    time: "9:00 am, Day-1",
    venue: "Workshop",
    image: "",
    url: "",
  },
  {
    event: "Paper Mache Studio",
    time: "1:00 pm, Day-1",
    venue: "DH-2",
    image: "",
    url: "",
  },
  {
    event: "Willow Wicker Studio",
    time: "3:30 pm, Day-1",
    venue: "DH-2",
    image: "",
    url: "",
  },
  {
    event: "Origami Studio",
    time: "9:00 am, Day-2",
    venue: "DH-2",
    image: "",
    url: "",
  },
  {
    event: "The Trained Cuisine (South)",
    time: "11.30 am, Day-2",
    venue: "Workshop",
    image: "",
    url: "",
  },
  {
    event: "Tattoo Making Studio",
    time: "3.30 pm, Day-2",
    venue: "DH-2",
    image: "",
    url: "",
  },
];

export const PerformingEvents = [
  {
    event: "Open Mic",
    time: "10:15 am, Day-2",
    venue: "Open Mic Stage",
    image: "",
    url: "",
  },
  {
    event: "Standup Comedy",
    time: "9:30 am, Day-1",
    venue: "Common Hall",
    image: "",
    url: "",
  },
  {
    event: "Mushaira/ Shayari",
    time: "11:10 am, Day-1",
    venue: "HT-3",
    image: "",
    url: "",
  },
  {
    event: "Theatrics",
    time: "11:00 am, Day-1",
    venue: "PF",
    image: "",
    url: "",
  },
  {
    event: "Monoacting",
    time: "11:30 am, Day-1",
    venue: "Common Hall",
    image: "",
    url: "",
  },
  {
    event: "Drama",
    time: "10:30 am, Day-2",
    venue: "Common Hall",
    image: "",
    url: "",
  },
  {
    event: "Mr and Ms Cultural Fest",
    time: "Day-1: Round-1(2:30 pm), Day-2: Finale(5:00 pm)",
    venue: "Main Stage",
    image: "",
    url: "",
  },
  {
    event: "Choreonight",
    time: "6.30 pm, Day-2",
    venue: "Main Stage",
    image: "",
    url: "",
  },
  {
    event: "Solo Dance (Eastern)",
    time: "3:00 pm, Day-1",
    venue: "Main Stage",
    image: "",
    url: "",
  },
  {
    event: "Duet Free Style Dance",
    time: "4:30 pm, Day-1",
    venue: "Main Stage",
    image: "",
    url: "",
  },
  {
    event: "Mimicry",
    time: "9:30 am, Day-2",
    venue: "Open Mic Stage",
    image: "",
    url: "",
  },
  {
    event: "Meme Making",
    time: "3.30 pm, Day-2",
    venue: "HT-1",
    image: "",
    url: "",
  },
  {
    event: "Drama",
    time: "10:30 am, Day-2",
    venue: "Common Hall",
    image: "",
    url: "",
  },
  {
    event: "Mr and Ms Cultural Fest",
    time: "Day-1: Round-1(2:30 pm), Day-2: Finale(5:00 pm)",
    venue: "Main Stage",
    image: "",
    url: "",
  },
  {
    event: "Choreonight",
    time: "6.30 pm, Day-2",
    venue: "Main Stage",
    image: "",
    url: "",
  },
];

export const day1Events = [
  {
    title: "Volaront , BGMI, Free Fire, Mortal Combat, Tekken 8, FIFA 23",
    startTime: "9:30 am",
    endTime: "4:00 pm",
    venue: "NA",
    exploreUrl: "#",
  },
  {
    title: "Tech Workshops",
    startTime: "10:00 am",
    endTime: "1:00 pm",
    venue: "LH (10 - 13)",
    exploreUrl: "#",
  },
  {
    title: "Tech Talks",
    startTime: "10:00 am",
    endTime: "11:30 am",
    venue: "LH (1 - 3)",
    exploreUrl: "#",
  },
  {
    title: "Art Competition",
    startTime: "10:00 am",
    endTime: "3:00 pm",
    venue: "Campus Parks",
    exploreUrl: "#",
  },
  {
    title: "Remote control Car Race",
    startTime: "10:30 am",
    endTime: "12:00 noon",
    venue: "Open Ground Near Chinar or Near Director's office",
    exploreUrl: "#",
  },
  {
    title: "Robo War Competition",
    startTime: "10:30 am",
    endTime: "12:00 noon",
    venue: "Common Hall",
    exploreUrl: "#",
  },
  {
    title: "Technical Tressure Hunt",
    startTime: "10:30 am",
    endTime: "2:00 pm",
    venue: "Campus Parks",
    exploreUrl: "#",
  },
  {
    title: "Tech Exhibition",
    startTime: "10:00 am",
    endTime: "2:00 pm",
    venue: "Library park",
    exploreUrl: "#",
  },
  {
    title: "Bomb Squad",
    startTime: "10:00 am",
    endTime: "11:30 am",
    venue: "Activity Centre Park",
    exploreUrl: "#",
  },
  {
    title: "Science Experiments",
    startTime: "10:00 am",
    endTime: "12:00 noon",
    venue: "Open Ground Near Chinar or Near Director's office",
    exploreUrl: "#",
  },
  {
    title: "Soapbox Car Racing",
    startTime: "11:00 am",
    endTime: "12:30 pm",
    venue: "Campus Roads",
    exploreUrl: "#",
  },
  {
    title: "Structure Battles",
    startTime: "02:00 pm",
    endTime: "03:30 pm",
    venue: "Common Hall",
    exploreUrl: "#",
  },
  {
    title: "Water Maze",
    startTime: "02:00 pm",
    endTime: "03:30 pm",
    venue: "Common Hall",
    exploreUrl: "#",
  },
  {
    title: "Egg Drop Challenge",
    startTime: "02:00 pm",
    endTime: "03:30 pm",
    venue: "Common Hall",
    exploreUrl: "#",
  },
  {
    title: "Symbola",
    startTime: "02:00 pm",
    endTime: "03:00 pm",
    venue: "LH 9",
    exploreUrl: "#",
  },
  {
    title: "Tech Talks",
    startTime: "02:00 pm",
    endTime: "03:00 pm",
    venue: "LH (1 - 3)",
    exploreUrl: "#",
  },
  {
    title: "Expert Talks",
    startTime: "02:30 pm",
    endTime: "03:00 pm",
    venue: "LH (4 - 10)",
    exploreUrl: "#",
  },
  {
    title: "Drone Soccer",
    startTime: "03:00 pm",
    endTime: "04:00 pm",
    venue: "Basket Ball Court",
    exploreUrl: "#",
  },
  {
    title: "Rocket Battles",
    startTime: "03:00 pm",
    endTime: "04:00 pm",
    venue: "NA",
    exploreUrl: "#",
  },
  {
    title: "Solar Cell Construction",
    startTime: "03:00 pm",
    endTime: "05:00 pm",
    venue: "NA",
    exploreUrl: "#",
  },
  {
    title: "Ideathons",
    startTime: "03:00 pm",
    endTime: "04:00 pm",
    venue: "HI-Tech 5",
    exploreUrl: "#",
  },
  {
    title: "Code Mania",
    startTime: "04:00 pm",
    endTime: "05:30 pm",
    venue: "LH 3",
    exploreUrl: "#",
  },
  {
    title: "Campus Cleaniness Drive",
    startTime: "04:00 pm",
    endTime: "05:30 pm",
    venue: "Campus",
    exploreUrl: "#",
  },
  {
    title: "Squid Game",
    startTime: "04:00 pm",
    endTime: "06:00 pm",
    venue: "Ground Near Mechanical Engineering Dept.",
    exploreUrl: "#",
  },
  {
    title: "USE The AI",
    startTime: "04:00 pm",
    endTime: "06:00 pm",
    venue: "L 1",
    exploreUrl: "#",
  },
  {
    title: "The Cheat Day",
    startTime: "04:00 pm",
    endTime: "06:00 pm",
    venue: "L 2",
    exploreUrl: "#",
  },
  {
    title: "Cultural Performances",
    startTime: "06:00 pm",
    endTime: "07:00 pm",
    venue: "Main Stage",
    exploreUrl: "#",
  },
  {
    title: "Programmable Led Light Show",
    startTime: "07:30 pm",
    endTime: "08:00 pm",
    venue: "NA",
    exploreUrl: "#",
  },
  {
    title: "Gaming Stalls",
    venue: "Main Ground",
    exploreUrl: "#",
    fullDay: true,
  },
  {
    title: "Photography Competition",
    venue: "Main Ground",
    exploreUrl: "#",
    fullDay: true,
  },
  {
    title: "Reel Making Competition",
    venue: "Main Ground",
    exploreUrl: "#",
    fullDay: true,
  },
  {
    title: "Short Movie making Competition",
    venue: "Main Ground",
    exploreUrl: "#",
    fullDay: true,
  },
];


export const day2Events = [
  {
    title: "30 sec reel making",
    startTime: "9:00 am",
    endTime: "6:30 pm",
    venue: "Campus",
    registerUrl: "#",
    exploreUrl: "#",
  },
  {
    title: "Live Photography",
    startTime: "9:00 am",
    endTime: "6:30 pm",
    venue: "Campus",
    registerUrl: "#",
    exploreUrl: "#",
  },
  {
    title: "Live Photography",
    startTime: "9:00 am",
    endTime: "6:30 pm",
    venue: "Campus",
    registerUrl: "#",
    exploreUrl: "#",
  },
  {
    title: "Live Photography",
    startTime: "9:00 am",
    endTime: "6:30 pm",
    venue: "Campus",
    registerUrl: "#",
    exploreUrl: "#",
  },
  {
    title: "Live Photography",
    startTime: "9:00 am",
    endTime: "6:30 pm",
    venue: "Campus",
    registerUrl: "#",
    exploreUrl: "#",
  },
  {
    title: "Live Photography",
    startTime: "9:00 am",
    endTime: "6:30 pm",
    venue: "Campus",
    registerUrl: "#",
    exploreUrl: "#",
  },
  {
    title: "Live Photography",
    startTime: "9:00 am",
    endTime: "6:30 pm",
    venue: "Campus",
    registerUrl: "#",
    exploreUrl: "#",
  },
  {
    title: "Live Photography",
    startTime: "9:00 am",
    endTime: "6:30 pm",
    venue: "Campus",
    registerUrl: "#",
    exploreUrl: "#",
  },
  {
    title: "Live Photography",
    startTime: "9:00 am",
    endTime: "6:30 pm",
    venue: "Campus",
    registerUrl: "#",
    exploreUrl: "#",
  },
];
